config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories

  post "reations",                to:"reactions#user_reaction",               as:"user_reaction"
  get "my_reactions",             to:"reactions#product_with_reactions",      as:"my_reactions"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :products

    validates :name, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
    has_and_belongs_to_many :categories
    has_many :reactions, dependent: :destroy
    has_many :users, through: :reactions
    accepts_nested_attributes_for :categories, reject_if: :no_name_category

    def count_with_kind(arg)
        number = self.reactions.where(kind: arg).count
        return "#{arg} - #{number}"
    end

    def find_kind_user_relation(user)
        self.reactions.find_by(user_id: user.id).kind
    end

    def no_name_category(attributes)
        attributes['name'].blank?
    end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :kind, acceptance: {
    accept: %w[ like dislike boring neutral uninterested interested ]
  }

  def self.kinds
    %w[ like dislike boring neutral uninterested interested ]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reactions
  has_many :products, through: :reactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :consultar_categorias, only: %i[ new edit create update ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.categories.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :size, {category_ids: []}, categories_attributes: [:id, :name])
    end

    def consultar_categorias
      @categories = Category.all
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    before_action :authenticate_user!

    def user_reaction
        @user = current_user
        @product = Product.find(params[:product_id])
        reaction = Reaction.find_by(user_id: @user.id, product_id: @product.id)
        if reaction
            return flash.now[:alert] = "Ya reaccionaste a este producto."
        else
            @new_reaction = Reaction.new(user_id: @user.id, product_id: @product.id, kind: params[:kind])
            respond_to do |format|
                if @new_reaction.save!
                    format.html {redirect_to product_path(@product), notice:"#{current_user.email} has stated that it #{@new_reaction.kind}"}
                else
                    format.html {redirect_to product_path(@product), status: :unprocessable_entity}
                end
            end
        end
    end

    def product_with_reactions
        @reactions = current_user.reactions
        product_ids = @reactions.map(&:product_id)
        @products = Product.where(id: product_ids)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <div class="container">
      <%= yield %>
    </div>




    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-5">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="col-5">
    <%= form.label :price, class:"form-label" %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="col-5">
    <%= form.label :size, class:"form-label" %>
    <%= form.number_field :size, class:"form-control" %>
  </div>

  <div>
    <%= form.label :category_ids, style: "display: block", class:"form-group" %>
    <div class="row">
      <%= form.collection_check_boxes(:category_ids, @categories, :id, :name) do |b| %>
        <div class="col-md-2">
          <span class="form-control my-2"><%= b.label {b.check_box + " " + b.text} %></span>
        </div>
      <% end %>
    </div>
  </div>

  <%= form.fields_for :categories do |ff| %>
    <div class="form-group col-5 mb-5">
      <%= ff.label :name, "Nombre Categoría", class:"form-label" %>
      <%= ff.text_field :name, class:"form-control" %>
    </div>
  <% end %>

  <div>
    <%= form.submit "Crear Producto", class:"btn btn-success" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= product.size %>
  </p>

  <div class="col-md-6">
    <ol class="list-group list-group-numbered list-group-horizontal">
      <% product.categories.each do |pc| %>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold"><%= pc.name %></div>
            <span class="badge bg-primary rounded-pill"><%= pc.products.count %></span>
          </div>
        </li>
      <% end %>
    </ol>
  </div>


</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path, class:"btn btn-dark" %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>
<div>
  <%= render "reactions/options" %>
</div>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/reactions/_counters.html.erb
<div>
    <ul>
        <% Reaction.kinds.each do |kind| %>
            <li><%= @product.count_with_kind(kind) %></li>
        <% end %>
    </ul>
</div>

app/views/reactions/_options.html.erb
<div>
    <ul>
        <% Reaction.kinds.each do |kind| %>
            <li><%= button_to "#{kind}", user_reaction_path(product_id: @product.id, kind: kind), method: :post %></li>
        <% end %>
    </ul>
</div>

app/views/reactions/product_with_reactions.html.erb
<h1>Products</h1>
<ul>
    <% @products.each do |product| %>
        <li>
            <%= product.name %> - <%= product.find_kind_user_relation(current_user) %>
            <p>
                <%= link_to "Show this product", product %>
            </p>
        </li>
    <% end %>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "Productos", products_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Categorias", categories_path, class:"nav-link" %>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to "Tus reacciones", my_reactions_path, class:"nav-link" %>
                </li>
            <% end %>
        </ul>
        <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown link
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
            </li>
        </ul>
    </div>
  </div>
</nav>